export type MlMigrationDecision = "migrar" | "adicionar" | "estudar" | "ignorar" | "aguardar";
export type MlOperationCategory = "read" | "write" | "destructive" | "financial" | "setup" | "composite";

export interface MlOperationMatrixEntry {
  operacao_sde: string;
  categoria: MlOperationCategory;
  risco_read_write: "read" | "write" | "destructive" | "financial" | "setup";
  endpoint_ou_recurso_oficial: string;
  status_decisao: MlMigrationDecision;
  justificativa: string;
  fonte_oficial: string;
  observacoes_para_ravi_dev: string;
  operacao_ravi: string | null;
}

export const confirmedOfficialContract = true;

const DOCS = "https://developers.mercadolivre.com.br/pt_br";

export const mlOfficialSources = {
  auth: `${DOCS}/gerenciamento-perguntas-respostas/autenticacao-e-autorizacao`,
  items: `${DOCS}/autenticacao-e-autorizacao/publicacao-de-produtos`,
  itemSearch: `${DOCS}/itens-e-buscas`,
  itemUpdate: `${DOCS}/produto-sincronizacao-de-publicacoes`,
  descriptions: `${DOCS}/api-docs-pt-br/descricao-de-produtos`,
  prices: `${DOCS}/produto-consulta-de-usuarios/api-de-precos`,
  visits: `${DOCS}/api-docs-pt-br/recurso-visits`,
  orders: `${DOCS}/gerenciamento-de-vendas`,
  billing: `${DOCS}/faturamento`,
  orderNotes: `${DOCS}/produto-consulta-de-usuarios/notas-de-ordens`,
  shipments: `${DOCS}/gerenciamento-de-envios`,
  questions: `${DOCS}/api-docs-pt-br/gerenciamento-perguntas-respostas`,
  packs: `${DOCS}/gerenciamento-de-vendas/gestao-packs`,
  messages: `${DOCS}/envio-personalizado/mensagens-post-venda`,
  claims: `${DOCS}/produto-consulta-de-usuarios/gerenciar-reclamacoes`,
  claimMessages: `${DOCS}/gerenciar-mensagem-de-uma-eclamacao`,
  returns: `${DOCS}/localizacao-e-moedas/gerenciar-devolucoes`,
  categories: `${DOCS}/categorizacao-de-produtos`,
  trends: `${DOCS}/relatorios-de-faturamento/tendencias`,
  highlights: `${DOCS}/relatorios-de-faturamento/mais-vendidos-no-mercado-livre`,
  productAds: `${DOCS}/product-ads-leitura`,
  productAdsCurrent: `${DOCS}/product-ads-para-catalogo-e-user-products-leitura`,
} as const;

export const mlOperationMatrix: MlOperationMatrixEntry[] = [
  entry(
    "auth | callback | status",
    "setup",
    "setup",
    "OAuth 2.0 authorization-code flow",
    "aguardar",
    "Autenticacao real esta fora da Fase 1.",
    mlOfficialSources.auth,
    null,
    "Nao ler ~/.ravi/sde-ml/token.json.",
  ),
  entry(
    "health",
    "composite",
    "read",
    "users/me + claims + shipments",
    "estudar",
    "O legado agrega varios recursos; o health inicial do App deve validar apenas o manifesto sem credencial.",
    mlOfficialSources.auth,
    null,
    "Adicionar health autenticado somente na Fase 2.",
  ),
  entry(
    "seller",
    "read",
    "read",
    "GET /users/me",
    "migrar",
    "Perfil autenticado confirmado pelo guia OAuth.",
    mlOfficialSources.auth,
    "ml.seller",
    "Retorno cru, sem persistencia.",
  ),
  entry(
    "vendas | pedidos",
    "read",
    "read",
    "GET /orders/search?seller={seller_id}",
    "migrar",
    "Orders search e filtros de seller sao oficiais.",
    mlOfficialSources.orders,
    "ml.orders",
    "Exige seller id explicito e paginacao limitada.",
  ),
  entry(
    "auditoria",
    "composite",
    "financial",
    "Orders + custos Tiny",
    "estudar",
    "A margem real combina ML e Tiny e nao e um endpoint do Mercado Livre.",
    mlOfficialSources.orders,
    null,
    "Migrar somente apos contrato de negocio e equivalencia comprovada.",
  ),
  entry(
    "pedido",
    "read",
    "read",
    "GET /orders/{order_id}",
    "migrar",
    "Detalhe de order confirmado.",
    mlOfficialSources.orders,
    "ml.order-get",
    "Aceitar HTTP 206 no onboarding de transporte posterior.",
  ),
  entry(
    "pedido-fiscal",
    "read",
    "financial",
    "GET /orders/{id}; GET /orders/billing-info/{site}/{billing_info_id}",
    "adicionar",
    "O endpoint legado /orders/{id}/billing_info foi depreciado; o fluxo novo e oficial.",
    mlOfficialSources.billing,
    "ml.order-billing",
    "Extrair buyer.billing_info.id da order antes da segunda consulta.",
  ),
  entry(
    "pedido-notas",
    "read",
    "read",
    "GET /orders/{order_id}/notes",
    "migrar",
    "Leitura de notas de order confirmada.",
    mlOfficialSources.orderNotes,
    "ml.order-notes",
    "Writes de notas nao faziam parte do comando legado.",
  ),
  entry(
    "anuncios",
    "read",
    "read",
    "GET /users/{seller_id}/items/search",
    "migrar",
    "Busca proprietaria por seller permanece suportada.",
    mlOfficialSources.itemSearch,
    "ml.items",
    "Paginar; nao usar busca publica por nickname.",
  ),
  entry(
    "anuncio",
    "read",
    "read",
    "GET /items/{item_id}",
    "migrar",
    "Detalhe de item confirmado.",
    mlOfficialSources.items,
    "ml.item-get",
    "IDs semanticamente validados por prefixo ML.",
  ),
  entry(
    "anuncios-multi",
    "read",
    "read",
    "GET /items?ids={ids}",
    "migrar",
    "Multiget oficial permanece suportado.",
    mlOfficialSources.itemSearch,
    "ml.items-get",
    "Limite local de 20 para equivalencia segura.",
  ),
  entry(
    "descricao",
    "read",
    "read",
    "GET /items/{item_id}/description",
    "migrar",
    "Descricao deixou de vir no detalhe de item e possui recurso proprio.",
    mlOfficialSources.descriptions,
    "ml.item-description",
    "Nao inferir descricao de /items.",
  ),
  entry(
    "visitas",
    "read",
    "read",
    "GET /items/{item_id}/visits/time_window",
    "migrar",
    "Janela de visitas oficial, maximo de 150 dias.",
    mlOfficialSources.visits,
    "ml.item-visits",
    "Validar last entre 1 e 150.",
  ),
  entry(
    "visitas-multi",
    "read",
    "read",
    "GET /visits/items?ids={ids}",
    "migrar",
    "Total multiget oficial confirmado.",
    mlOfficialSources.visits,
    "ml.items-visits",
    "Limite local de 50.",
  ),
  entry(
    "(novo) item-prices",
    "read",
    "financial",
    "GET /items/{item_id}/prices",
    "adicionar",
    "A documentacao manda consultar o recurso Prices em vez dos campos de /items.",
    mlOfficialSources.prices,
    "ml.item-prices",
    "Somente leitura nesta fase.",
  ),
  entry(
    "perguntas",
    "read",
    "read",
    "GET /questions/search?seller_id={seller_id}&api_version=4",
    "migrar",
    "Busca de perguntas recebidas confirmada.",
    mlOfficialSources.questions,
    "ml.questions",
    "Usar api_version=4.",
  ),
  entry(
    "responder",
    "write",
    "write",
    "POST /answers",
    "migrar",
    "Resposta oficial; comunicacao externa irreversivel.",
    mlOfficialSources.questions,
    "ml.question-answer",
    "Permissao de comunicacao e confirmacao explicita.",
  ),
  entry(
    "envio",
    "read",
    "read",
    "GET /shipments/{shipment_id}",
    "migrar",
    "Shipment atual exige x-format-new: true.",
    mlOfficialSources.shipments,
    "ml.shipment-get",
    "Enviar o header oficial.",
  ),
  entry(
    "envio-custos",
    "financial",
    "financial",
    "GET /shipments/{shipment_id}/costs",
    "migrar",
    "Custos finais de sender/receiver sao oficiais.",
    mlOfficialSources.shipments,
    "ml.shipment-costs",
    "Permissao financeira read separada.",
  ),
  entry(
    "envio-historico",
    "read",
    "read",
    "GET /shipments/{shipment_id}/history",
    "migrar",
    "Historico de status confirmado.",
    mlOfficialSources.shipments,
    "ml.shipment-history",
    "Enviar x-format-new: true.",
  ),
  entry(
    "envio-etiqueta",
    "read",
    "read",
    "GET /shipment_labels?shipment_ids={ids}",
    "estudar",
    "O recurso existe, mas exige contrato binario/artifact e formatos ZPL/PDF.",
    mlOfficialSources.shipments,
    null,
    "Nao embutir binario em JSON nem escrever arquivo arbitrario nesta fase.",
  ),
  entry(
    "envio-resolve",
    "composite",
    "read",
    "shipments + orders/search",
    "estudar",
    "Fallback webhook->order e logica composta do legado, nao um endpoint unico.",
    mlOfficialSources.shipments,
    null,
    "Migrar quando o contrato de webhook estiver no app nativo.",
  ),
  entry(
    "postagem *",
    "composite",
    "financial",
    "Mercado Livre + Tiny + SEFAZ + Labelary",
    "aguardar",
    "Emissao fiscal e postagem atravessam dominios e podem ser irreversiveis.",
    mlOfficialSources.shipments,
    null,
    "Permanece no legado; nao pertence ao cliente ML isolado.",
  ),
  entry(
    "categoria",
    "read",
    "read",
    "GET /categories/{category_id}",
    "migrar",
    "Detalhe de categoria confirmado.",
    mlOfficialSources.categories,
    "ml.category-get",
    "Recurso publico, mas o cliente mantem auth fail-closed uniforme.",
  ),
  entry(
    "tendencias",
    "read",
    "read",
    "GET /trends/{site_id}[/{category_id}]",
    "migrar",
    "Tendencias oficiais por site e categoria.",
    mlOfficialSources.trends,
    "ml.trends",
    "Site default MLB, explicito no CLI.",
  ),
  entry(
    "destaques",
    "read",
    "read",
    "GET /highlights/{site_id}/category/{category_id}",
    "migrar",
    "Top 20 oficial por categoria.",
    mlOfficialSources.highlights,
    "ml.highlights",
    "Nao tratar como ranking financeiro.",
  ),
  entry(
    "pack",
    "read",
    "read",
    "GET /packs/{pack_id}",
    "migrar",
    "Pack atual relaciona orders e shipment.",
    mlOfficialSources.packs,
    "ml.pack-get",
    "Sem expandir orders automaticamente.",
  ),
  entry(
    "anuncio-criar",
    "write",
    "write",
    "POST /items",
    "migrar",
    "Criacao classica continua documentada, com aviso de User Products para novos fluxos.",
    mlOfficialSources.items,
    "ml.item-create",
    "Corpo explicito, confirmacao e auth fechada.",
  ),
  entry(
    "anuncio-editar",
    "write",
    "write",
    "PUT /items/{item_id}",
    "migrar",
    "Atualizacao parcial confirmada.",
    mlOfficialSources.itemUpdate,
    "ml.item-update",
    "Bloquear price, status e deleted no patch generico.",
  ),
  entry(
    "anuncio-descricao",
    "write",
    "write",
    "POST|PUT /items/{item_id}/description",
    "adicionar",
    "A API diferencia criacao e substituicao.",
    mlOfficialSources.descriptions,
    "ml.description-create | ml.description-update",
    "Nao implementar upsert ambiguo.",
  ),
  entry(
    "anuncio-preco",
    "financial",
    "financial",
    "POST /items/{item_id}/prices/standard",
    "aguardar",
    "A propria documentacao atual marca a API de escrita standard como ainda indisponivel.",
    mlOfficialSources.prices,
    null,
    "Nao copiar o endpoint alegado pelo legado ate a fonte oficial liberar.",
  ),
  entry(
    "anuncio-pausar | anuncio-ativar",
    "write",
    "write",
    "PUT /items/{item_id} status=paused|active",
    "migrar",
    "Estados reversiveis confirmados.",
    mlOfficialSources.itemUpdate,
    "ml.item-pause | ml.item-activate",
    "Comandos separados do patch generico.",
  ),
  entry(
    "anuncio-fechar",
    "destructive",
    "destructive",
    "PUT /items/{item_id} status=closed",
    "migrar",
    "Closed e terminal e nao pode ser reativado.",
    mlOfficialSources.itemUpdate,
    "ml.item-close",
    "Permissao destructive e confirmacao propria.",
  ),
  entry(
    "anuncio-deletar",
    "destructive",
    "destructive",
    "PUT status=closed; PUT deleted=true",
    "migrar",
    "Fluxo oficial de dois passos e irreversivel.",
    mlOfficialSources.itemUpdate,
    "ml.item-delete",
    "Pode falhar parcialmente entre os passos; retorno preserva as duas respostas.",
  ),
  entry(
    "ads-advertiser",
    "financial",
    "financial",
    "GET /advertising/advertisers?product_id=PADS",
    "migrar",
    "Endpoint atual usa Api-Version: 1.",
    mlOfficialSources.productAds,
    "ml.ads-advertisers",
    "Nenhum advertiser id hard-coded.",
  ),
  entry(
    "ads-campanhas",
    "financial",
    "financial",
    "GET /advertising/{site}/advertisers/{advertiser}/product_ads/campaigns/search",
    "migrar",
    "Search atual usa Api-Version: 2.",
    mlOfficialSources.productAdsCurrent,
    "ml.ads-campaigns",
    "Datas obrigatorias apenas ao solicitar metricas.",
  ),
  entry(
    "ads-anuncios",
    "financial",
    "financial",
    "GET .../product_ads/ad_groups/search",
    "adicionar",
    "Ads search antigo foi removido; ad_group_id e o identificador atual.",
    mlOfficialSources.productAdsCurrent,
    "ml.ads-ad-groups",
    "Nao usar endpoints ads/search desativados.",
  ),
  entry(
    "ads-campanha-criar | ads-campanha-editar | ads-anuncio-mover",
    "financial",
    "financial",
    "Product Ads write surface",
    "estudar",
    "A leitura atual foi confirmada, mas o endpoint atual de escrita nao ficou inequívoco na fonte oficial consultada.",
    mlOfficialSources.productAdsCurrent,
    null,
    "Bloquear mutacoes de budget/status; nao inferir endpoint legado.",
  ),
  entry(
    "pack-mensagens",
    "read",
    "read",
    "GET /messages/packs/{pack}/sellers/{seller}?tag=post_sale",
    "migrar",
    "Consulta pós-venda atual confirmada.",
    mlOfficialSources.messages,
    "ml.messages",
    "Paginar e preservar conversation_status.",
  ),
  entry(
    "pack-responder",
    "write",
    "write",
    "POST /messages/packs/{pack}/sellers/{seller}?tag=post_sale",
    "adicionar",
    "Desde 2026 o destinatario MLB pode ser o Agent User ID, nao o buyer id legado.",
    mlOfficialSources.messages,
    "ml.message-send",
    "Exigir to-user explicito e confirmacao; nao codificar ID do comprador.",
  ),
  entry(
    "reclamacoes",
    "read",
    "read",
    "GET /post-purchase/v1/claims/search",
    "migrar",
    "Busca atual exige filtro acotado; status sozinho e desencorajado.",
    mlOfficialSources.claims,
    "ml.claims",
    "Exigir seller id e players.role=respondent.",
  ),
  entry(
    "reclamacao",
    "read",
    "read",
    "GET /post-purchase/v1/claims/{claim_id}",
    "migrar",
    "Detalhe de claim confirmado.",
    mlOfficialSources.claims,
    "ml.claim-get",
    "Sem acao de resolucao nesta fase.",
  ),
  entry(
    "reclamacao-mensagens",
    "read",
    "read",
    "GET /post-purchase/v1/claims/{claim_id}/messages",
    "migrar",
    "Mensagens do claim confirmadas.",
    mlOfficialSources.claimMessages,
    "ml.claim-messages",
    "Read-only.",
  ),
  entry(
    "reclamacao-devolucao",
    "read",
    "read",
    "GET /post-purchase/v2/claims/{claim_id}/returns",
    "adicionar",
    "Returns atual usa v2.",
    mlOfficialSources.returns,
    "ml.claim-return",
    "Nao copiar v1 do legado se presente.",
  ),
];

function entry(
  operacao_sde: string,
  categoria: MlOperationCategory,
  risco_read_write: MlOperationMatrixEntry["risco_read_write"],
  endpoint_ou_recurso_oficial: string,
  status_decisao: MlMigrationDecision,
  justificativa: string,
  fonte_oficial: string,
  operacao_ravi: string | null,
  observacoes_para_ravi_dev: string,
): MlOperationMatrixEntry {
  return {
    operacao_sde,
    categoria,
    risco_read_write,
    endpoint_ou_recurso_oficial,
    status_decisao,
    justificativa,
    fonte_oficial,
    observacoes_para_ravi_dev,
    operacao_ravi,
  };
}
