export type EventTopicClassification =
  | "public-trigger"
  | "replay-only"
  | "internal-control"
  | "workqueue"
  | "external-stream";

export interface EventTopicRegistryEntry {
  id: string;
  pattern: string;
  classification: EventTopicClassification;
  owner: string;
  description: string;
  replay: boolean;
  triggerCatalog: boolean;
  notes?: string[];
}

const EVENT_TOPIC_REGISTRY: readonly EventTopicRegistryEntry[] = [
  {
    id: "session.prompt",
    pattern: "ravi.session.*.prompt",
    classification: "workqueue",
    owner: "runtime",
    description: "Session prompt workqueue subject.",
    replay: false,
    triggerCatalog: false,
    notes: ["Stored in the SESSION_PROMPTS stream; intentionally excluded from RAVI_EVENTS to avoid overlap."],
  },
  {
    id: "session.response",
    pattern: "ravi.session.*.response",
    classification: "replay-only",
    owner: "runtime",
    description: "Assistant response emitted by a runtime session.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.runtime",
    pattern: "ravi.session.*.runtime",
    classification: "replay-only",
    owner: "runtime",
    description: "Structured runtime lifecycle events for a session.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.claude",
    pattern: "ravi.session.*.claude",
    classification: "replay-only",
    owner: "runtime",
    description: "Provider-native Claude event mirror for debugging.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.tool",
    pattern: "ravi.session.*.tool",
    classification: "replay-only",
    owner: "runtime",
    description: "Tool start/end events emitted by a session runtime.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.stream",
    pattern: "ravi.session.*.stream",
    classification: "replay-only",
    owner: "runtime",
    description: "Text delta stream for live clients.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.delivery",
    pattern: "ravi.session.*.delivery",
    classification: "replay-only",
    owner: "runtime",
    description: "Per-session delivery observation events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.adapter",
    pattern: "ravi.session.*.adapter.>",
    classification: "replay-only",
    owner: "runtime",
    description: "Runtime adapter event namespace.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.control",
    pattern: "ravi.session.runtime.control",
    classification: "internal-control",
    owner: "runtime",
    description: "Runtime control requests such as steering and follow-up.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.abort",
    pattern: "ravi.session.abort",
    classification: "internal-control",
    owner: "runtime",
    description: "Abort request for an active session.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.reset.requested",
    pattern: "ravi.session.reset.requested",
    classification: "internal-control",
    owner: "sessions",
    description: "Session reset request audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.reset.completed",
    pattern: "ravi.session.reset.completed",
    classification: "internal-control",
    owner: "sessions",
    description: "Session reset completion audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.delete.requested",
    pattern: "ravi.session.delete.requested",
    classification: "internal-control",
    owner: "sessions",
    description: "Session delete request audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.delete.completed",
    pattern: "ravi.session.delete.completed",
    classification: "internal-control",
    owner: "sessions",
    description: "Session delete completion audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.prune.requested",
    pattern: "ravi.session.prune.requested",
    classification: "internal-control",
    owner: "sessions",
    description: "Session prune request audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.prune.completed",
    pattern: "ravi.session.prune.completed",
    classification: "internal-control",
    owner: "sessions",
    description: "Session prune completion audit event.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "session.model.changed",
    pattern: "ravi.session.model.changed",
    classification: "internal-control",
    owner: "sessions",
    description: "Session model override change notification.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "presence",
    pattern: "ravi.presence.>",
    classification: "replay-only",
    owner: "channels",
    description: "Presence lifecycle events such as typing state.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "approval",
    pattern: "ravi.approval.>",
    classification: "public-trigger",
    owner: "runtime",
    description: "Approval request and response events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "audit",
    pattern: "ravi.audit.>",
    classification: "public-trigger",
    owner: "permissions",
    description: "Audit events such as permission denials.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "inbound",
    pattern: "ravi.inbound.>",
    classification: "public-trigger",
    owner: "channels",
    description: "Normalized inbound channel interaction events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "outbound",
    pattern: "ravi.outbound.>",
    classification: "replay-only",
    owner: "channels",
    description: "Outbound channel delivery and reaction requests.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "media.send",
    pattern: "ravi.media.send",
    classification: "replay-only",
    owner: "channels",
    description: "Outbound media send request.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "stickers.send",
    pattern: "ravi.stickers.send",
    classification: "replay-only",
    owner: "channels",
    description: "Outbound sticker send request.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "contacts",
    pattern: "ravi.contacts.>",
    classification: "public-trigger",
    owner: "contacts",
    description: "Contact lifecycle and pending review events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "chats",
    pattern: "ravi.chats.>",
    classification: "public-trigger",
    owner: "channels",
    description: "Chat lifecycle, pending review and chat tag events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "instances",
    pattern: "ravi.instances.>",
    classification: "public-trigger",
    owner: "channels",
    description: "Channel instance lifecycle and unregistered instance events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "whatsapp",
    pattern: "ravi.whatsapp.>",
    classification: "replay-only",
    owner: "channels",
    description: "WhatsApp instance connection and QR events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "config.changed",
    pattern: "ravi.config.changed",
    classification: "internal-control",
    owner: "config",
    description: "Global config changed notification.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "triggers",
    pattern: "ravi.triggers.>",
    classification: "internal-control",
    owner: "triggers",
    description: "Trigger runner refresh and test events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "sessions.followup",
    pattern: "ravi.sessions.followup.>",
    classification: "public-trigger",
    owner: "sessions",
    description: "Session follow-up lifecycle events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "cron",
    pattern: "ravi.cron.>",
    classification: "internal-control",
    owner: "cron",
    description: "Cron runner refresh and manual trigger events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "heartbeat",
    pattern: "ravi.heartbeat.>",
    classification: "internal-control",
    owner: "heartbeat",
    description: "Heartbeat runner refresh events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "runtime",
    pattern: "ravi.runtime.>",
    classification: "replay-only",
    owner: "runtime",
    description: "Runtime health and pool telemetry events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "cli.standalone",
    pattern: "ravi._cli.cli.>",
    classification: "public-trigger",
    owner: "cli",
    description: "Standalone CLI command audit events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "cli.session",
    pattern: "ravi.*.cli.*.*",
    classification: "public-trigger",
    owner: "cli",
    description: "Session-scoped CLI command audit events.",
    replay: false,
    triggerCatalog: true,
    notes: ["Not added to RAVI_EVENTS because wildcarding this pattern overlaps broad session subjects."],
  },
  {
    id: "inbox",
    pattern: "ravi.inbox.>",
    classification: "public-trigger",
    owner: "inbox",
    description: "Native local inbox events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "console",
    pattern: "ravi.console.>",
    classification: "public-trigger",
    owner: "console",
    description: "Console delivery mirror events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "watch",
    pattern: "ravi.watch.>",
    classification: "public-trigger",
    owner: "watch",
    description: "Normalized watch events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "tasks",
    pattern: "ravi.task.>",
    classification: "public-trigger",
    owner: "tasks",
    description: "Task lifecycle events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "tags",
    pattern: "ravi.tags.>",
    classification: "public-trigger",
    owner: "tags",
    description: "Tag rule application events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "tts.request",
    pattern: "ravi.tts",
    classification: "public-trigger",
    owner: "audio",
    description: "Text-to-speech generation request.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "tts.lifecycle",
    pattern: "ravi.tts.*",
    classification: "public-trigger",
    owner: "audio",
    description: "Text-to-speech generation lifecycle events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "artifacts",
    pattern: "ravi.artifacts.>",
    classification: "public-trigger",
    owner: "artifacts",
    description: "Artifact lifecycle events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "meetings",
    pattern: "ravi.meetings.>",
    classification: "public-trigger",
    owner: "meetings",
    description: "Meeting lifecycle and artifact events.",
    replay: true,
    triggerCatalog: true,
  },
  {
    id: "hooks",
    pattern: "ravi.hooks.>",
    classification: "internal-control",
    owner: "hooks",
    description: "Hook runtime control events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "rtk.rewrite",
    pattern: "ravi.rtk.>",
    classification: "replay-only",
    owner: "hooks",
    description: "RTK hook rewrite audit events.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "work_objects",
    pattern: "ravi.work_objects.>",
    classification: "replay-only",
    owner: "work-objects",
    description: "Ravi work object request subjects for rich interactive objects.",
    replay: true,
    triggerCatalog: false,
  },
  {
    id: "work_objects.compat",
    pattern: "omni.work_objects.>",
    classification: "external-stream",
    owner: "work-objects",
    description: "Omni-compatible work object request subjects.",
    replay: false,
    triggerCatalog: false,
  },
  {
    id: "omni.message.received",
    pattern: "message.received.>",
    classification: "external-stream",
    owner: "omni",
    description: "Omni inbound message JetStream subjects consumed by Ravi.",
    replay: false,
    triggerCatalog: false,
  },
  {
    id: "omni.reaction.received",
    pattern: "reaction.received.>",
    classification: "external-stream",
    owner: "omni",
    description: "Omni inbound reaction JetStream subjects consumed by Ravi.",
    replay: false,
    triggerCatalog: false,
  },
  {
    id: "omni.presence.typing",
    pattern: "presence.typing",
    classification: "external-stream",
    owner: "omni",
    description: "Omni channel typing presence subject.",
    replay: false,
    triggerCatalog: false,
  },
  {
    id: "omni.chat.unread",
    pattern: "chat.unread-updated",
    classification: "external-stream",
    owner: "omni",
    description: "Omni chat unread counter update subject.",
    replay: false,
    triggerCatalog: false,
  },
  {
    id: "omni.instance",
    pattern: "instance.>",
    classification: "external-stream",
    owner: "omni",
    description: "Omni instance lifecycle stream subjects.",
    replay: false,
    triggerCatalog: false,
  },
] as const;

function cloneEntry(entry: EventTopicRegistryEntry): EventTopicRegistryEntry {
  return {
    ...entry,
    ...(entry.notes ? { notes: [...entry.notes] } : {}),
  };
}

export function getEventTopicRegistry(): EventTopicRegistryEntry[] {
  return EVENT_TOPIC_REGISTRY.map(cloneEntry);
}

export function getRaviEventsReplaySubjects(): string[] {
  return EVENT_TOPIC_REGISTRY.filter((entry) => entry.replay).map((entry) => entry.pattern);
}

export function getPublicTriggerTopicPatterns(): string[] {
  return EVENT_TOPIC_REGISTRY.filter((entry) => entry.triggerCatalog).map((entry) => entry.pattern);
}
