export type MerchantMigrationDecision = "migrar" | "adicionar" | "estudar" | "ignorar" | "aguardar";
export type MerchantOperationRisk = "read" | "write" | "destructive" | "financial" | "setup";

export interface MerchantOperationMatrixEntry {
  operacao_sde: string;
  categoria: string;
  risco_read_write: MerchantOperationRisk;
  endpoint_ou_recurso_oficial: string;
  status_decisao: MerchantMigrationDecision;
  justificativa: string;
  fonte_oficial: string;
  observacoes_para_ravi_dev: string;
  operacao_ravi: string | null;
}

interface MerchantOperationGroup extends Omit<MerchantOperationMatrixEntry, "operacao_sde"> {
  operacoes_sde: string[];
}

const DISCOVERY = "https://merchantapi.googleapis.com/$discovery/rest";
const REST_REFERENCE = "https://developers.google.com/merchant/api/reference/rest";
const VERSIONING = "https://developers.google.com/merchant/api/guides/versioning";

export const merchantOfficialContract = {
  confirmed: true,
  verifiedAt: "2026-07-13",
  baseUrl: "https://merchantapi.googleapis.com",
  oauthScope: "https://www.googleapis.com/auth/content",
  stableSubApis: [
    "accounts_v1",
    "conversions_v1",
    "datasources_v1",
    "inventories_v1",
    "issueresolution_v1",
    "lfp_v1",
    "notifications_v1",
    "ordertracking_v1",
    "products_v1",
    "promotions_v1",
    "quota_v1",
    "reports_v1",
  ],
  limitedSubApis: ["productstudio_v1alpha", "reviews_v1alpha"],
  sources: ["https://discovery.googleapis.com/discovery/v1/apis?name=merchantapi", VERSIONING, REST_REFERENCE],
} as const;

const groups: MerchantOperationGroup[] = [
  {
    operacoes_sde: ["auth-url", "auth", "config", "health"],
    categoria: "setup",
    risco_read_write: "setup",
    endpoint_ou_recurso_oficial: "OAuth 2.0 + developer registration",
    status_decisao: "aguardar",
    justificativa: "Token, onboarding de credencial e autenticação real estão fora da Fase 1.",
    fonte_oficial: "https://developers.google.com/merchant/api/guides/authorization/access-your-account",
    observacoes_para_ravi_dev: "Falhar antes do fetch e nunca ler merchant-credentials.json ou merchant-token.json.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["accounts", "account"],
    categoria: "accounts",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET accounts/v1/accounts | GET accounts/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Listagem e detalhe de conta têm contrato v1 estável.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts`,
    observacoes_para_ravi_dev: "Paginar accounts.list e aceitar somente account id numérico.",
    operacao_ravi: "merchant.accounts | merchant.account-get",
  },
  {
    operacoes_sde: ["issues", "account-issues"],
    categoria: "account-issues",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET accounts/v1/{parent}/issues",
    status_decisao: "migrar",
    justificativa: "Issues de conta têm recurso v1 estável.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts.issues/list`,
    observacoes_para_ravi_dev: "A leitura nativa não executa ações de resolução.",
    operacao_ravi: "merchant.account-issues",
  },
  {
    operacoes_sde: ["products", "product", "product-statuses"],
    categoria: "products",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET products/v1/{parent}/products | GET products/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Products v1 retorna produto processado e ProductStatus.",
    fonte_oficial: `${REST_REFERENCE}/products_v1/accounts.products`,
    observacoes_para_ravi_dev: "Usar base64url para ids com caracteres reservados; não presumir channel do v1beta.",
    operacao_ravi: "merchant.products | merchant.product-get",
  },
  {
    operacoes_sde: [
      "report",
      "performance",
      "pricing",
      "best-sellers",
      "product-issues",
      "non-product-performance",
      "price-insights",
      "topic-trends",
    ],
    categoria: "reports",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "POST reports/v1/{parent}/reports:search",
    status_decisao: "migrar",
    justificativa: "POST é transporte read-only para Merchant API Query Language.",
    fonte_oficial: `${REST_REFERENCE}/reports_v1/accounts.reports/search`,
    observacoes_para_ravi_dev: "Expor query explícita; templates derivados podem ser adicionados sem novo endpoint.",
    operacao_ravi: "merchant.report-search",
  },
  {
    operacoes_sde: ["promotions", "promotion"],
    categoria: "promotions",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET promotions/v1/{parent}/promotions | GET promotions/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Leitura de promoções está confirmada em promotions v1.",
    fonte_oficial: `${REST_REFERENCE}/promotions_v1/accounts.promotions`,
    observacoes_para_ravi_dev: "Não inferir delete: promotions v1 expõe apenas get, list e insert.",
    operacao_ravi: "merchant.promotions | merchant.promotion-get",
  },
  {
    operacoes_sde: ["data-sources", "data-source"],
    categoria: "data-sources",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET datasources/v1/{parent}/dataSources | GET datasources/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Leitura de fontes está confirmada em datasources v1.",
    fonte_oficial: `${REST_REFERENCE}/datasources_v1/accounts.dataSources`,
    observacoes_para_ravi_dev: "Retornar configuração; nunca imprimir password de fetch caso o provedor o devolva.",
    operacao_ravi: "merchant.data-sources | merchant.data-source-get",
  },
  {
    operacoes_sde: ["file-upload-latest"],
    categoria: "data-source-file-uploads",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "GET datasources/v1/{name} (accounts.dataSources.fileUploads.get)",
    status_decisao: "adicionar",
    justificativa: "Método v1 confirmado, mas não integra a superfície diária mínima desta Fase 1.",
    fonte_oficial: `${DISCOVERY}?version=datasources_v1`,
    observacoes_para_ravi_dev: "Adicionar como leitura quando houver caso operacional no app novo.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["product-insert", "product-patch"],
    categoria: "product-inputs",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "POST products/v1/{parent}/productInputs:insert | PATCH products/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Contratos v1 confirmados; execução permanece fechada sem credencial.",
    fonte_oficial: `${REST_REFERENCE}/products_v1/accounts.productInputs`,
    observacoes_para_ravi_dev:
      "Exigir confirmação, dataSource e updateMask explícito no patch; primary feed continua Tray.",
    operacao_ravi: "merchant.product-insert | merchant.product-patch",
  },
  {
    operacoes_sde: ["product-delete"],
    categoria: "product-inputs",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "DELETE products/v1/{name}?dataSource=...",
    status_decisao: "migrar",
    justificativa: "Delete de ProductInput existe e deve ficar isolado de writes comuns.",
    fonte_oficial: `${REST_REFERENCE}/products_v1/accounts.productInputs/delete`,
    observacoes_para_ravi_dev: "Permissão destrutiva e confirmação obrigatórias; sem chamada real na Fase 1.",
    operacao_ravi: "merchant.product-delete",
  },
  {
    operacoes_sde: ["data-source-create", "data-source-update", "data-source-fetch"],
    categoria: "data-sources",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "POST/PATCH datasources/v1/... | POST datasources/v1/{name}:fetch",
    status_decisao: "migrar",
    justificativa: "Métodos v1 confirmados e não destrutivos por contrato HTTP.",
    fonte_oficial: `${REST_REFERENCE}/datasources_v1/accounts.dataSources`,
    observacoes_para_ravi_dev:
      "Ainda são alto risco operacional porque podem alterar ou disparar sincronização do feed.",
    operacao_ravi: "merchant.data-source-create | merchant.data-source-update | merchant.data-source-fetch",
  },
  {
    operacoes_sde: ["data-source-delete"],
    categoria: "data-sources",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "DELETE datasources/v1/{name}",
    status_decisao: "migrar",
    justificativa: "Delete de fonte pode interromper sincronização e tem contrato v1 próprio.",
    fonte_oficial: `${REST_REFERENCE}/datasources_v1/accounts.dataSources/delete`,
    observacoes_para_ravi_dev: "Permissão destrutiva e confirmação obrigatórias.",
    operacao_ravi: "merchant.data-source-delete",
  },
  {
    operacoes_sde: ["promotion-insert"],
    categoria: "promotions",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "POST promotions/v1/{parent}/promotions:insert",
    status_decisao: "migrar",
    justificativa: "Insert está confirmado; não existe promotion delete em v1.",
    fonte_oficial: `${REST_REFERENCE}/promotions_v1/accounts.promotions/insert`,
    observacoes_para_ravi_dev: "O body é InsertPromotionRequest, não um Promotion solto.",
    operacao_ravi: "merchant.promotion-insert",
  },
  {
    operacoes_sde: [
      "business-info",
      "shipping",
      "programs",
      "return-policies",
      "program",
      "tos",
      "tos-latest",
      "homepage",
      "sub-accounts",
      "regions",
      "region",
      "return-policy",
      "autofeed",
      "business-identity",
      "email-prefs",
      "automatic-improvements",
      "omnichannel-list",
      "omnichannel",
      "checkout-settings",
      "relationships",
      "relationship",
      "services-list",
      "service",
    ],
    categoria: "account-settings",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Accounts v1 resources",
    status_decisao: "adicionar",
    justificativa:
      "Os recursos estão confirmados em accounts v1, mas não pertencem ao núcleo diário mínimo já implementado.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev:
      "Adicionar por fluxo de negócio, com paginação e retorno tipado, sem espelhar endpoints cegamente.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: [
      "account-update",
      "homepage-update",
      "homepage-claim",
      "homepage-unclaim",
      "region-create",
      "region-update",
      "return-policy-create",
      "autofeed-update",
      "business-identity-update",
      "email-prefs-update",
      "business-info-update",
      "shipping-insert",
      "account-create-configure",
      "account-test-create",
      "automatic-improvements-update",
      "omnichannel-create",
      "omnichannel-update",
      "omnichannel-verify",
      "lfp-provider-link",
      "checkout-settings-create",
      "checkout-settings-update",
      "regions-batch-create",
      "regions-batch-update",
      "relationship-update",
      "service-propose",
      "service-approve",
      "service-reject",
      "verify-self",
    ],
    categoria: "account-settings",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Accounts v1 mutating methods",
    status_decisao: "adicionar",
    justificativa:
      "Métodos oficiais existem, mas exigem desenho de fluxo e confirmação específicos antes de exposição.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev:
      "Separar grants por recurso; não liberar via merchant:write genérico sem revisão de cada fluxo.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: [
      "account-delete",
      "region-delete",
      "return-policy-delete",
      "checkout-settings-delete",
      "regions-batch-delete",
    ],
    categoria: "account-settings",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Accounts v1 delete methods",
    status_decisao: "adicionar",
    justificativa: "Métodos confirmados, irreversíveis ou de alto impacto operacional.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev: "Exigir permissão destrutiva, confirmação e eventual dry-run específico.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["local-inventories", "regional-inventories"],
    categoria: "inventories",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Inventories v1 list methods",
    status_decisao: "adicionar",
    justificativa: "Inventories v1 é estável e confirma leitura local/regional.",
    fonte_oficial: `${DISCOVERY}?version=inventories_v1`,
    observacoes_para_ravi_dev:
      "A conta atual pode não estar habilitada; tratar 403 como capability externa, não fallback para legado.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["local-inventory-insert", "regional-inventory-insert"],
    categoria: "inventories",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Inventories v1 insert methods",
    status_decisao: "adicionar",
    justificativa: "Writes oficiais existem, mas estoque é domínio sensível e requer integração com a SSoT.",
    fonte_oficial: `${DISCOVERY}?version=inventories_v1`,
    observacoes_para_ravi_dev: "Não executar sem alinhamento com Tiny/Tray e permissão de estoque dedicada.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["local-inventory-delete", "regional-inventory-delete"],
    categoria: "inventories",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Inventories v1 delete methods",
    status_decisao: "adicionar",
    justificativa: "Deletes oficiais existem e removem disponibilidade regional/local.",
    fonte_oficial: `${DISCOVERY}?version=inventories_v1`,
    observacoes_para_ravi_dev: "Permissão destrutiva e coordenação com a SSoT de estoque são obrigatórias.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["conversion-sources", "conversion-source"],
    categoria: "conversion-sources",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Conversions v1 get/list methods",
    status_decisao: "adicionar",
    justificativa: "Conversions v1 é estável e confirma leitura.",
    fonte_oficial: `${DISCOVERY}?version=conversions_v1`,
    observacoes_para_ravi_dev: "Modelar por caso de atribuição antes de expor no app diário.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["conversion-source-create", "conversion-source-update", "conversion-source-undelete"],
    categoria: "conversion-sources",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Conversions v1 create/patch/undelete methods",
    status_decisao: "adicionar",
    justificativa: "Métodos oficiais confirmados; afetam mensuração e exigem confirmação.",
    fonte_oficial: `${DISCOVERY}?version=conversions_v1`,
    observacoes_para_ravi_dev: "Permissão de conversões separada de feed/produtos.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["conversion-source-delete"],
    categoria: "conversion-sources",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Conversions v1 delete method",
    status_decisao: "adicionar",
    justificativa: "Delete afeta mensuração e deve ficar isolado.",
    fonte_oficial: `${DISCOVERY}?version=conversions_v1`,
    observacoes_para_ravi_dev: "Permissão destrutiva e confirmação obrigatórias.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["users", "user"],
    categoria: "account-users",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Accounts v1 users get/list",
    status_decisao: "adicionar",
    justificativa: "Leitura de usuários está confirmada em accounts v1.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts.users`,
    observacoes_para_ravi_dev: "Dados de identidade pedem redaction e permissão própria.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["user-create", "user-update"],
    categoria: "account-users",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Accounts v1 users create/patch",
    status_decisao: "adicionar",
    justificativa: "Gerenciamento de acesso é write sensível e não cabe no grant genérico de Merchant.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts.users`,
    observacoes_para_ravi_dev: "Exigir permissão administrativa específica e confirmação.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["user-delete"],
    categoria: "account-users",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "DELETE accounts/v1/{name=accounts/*/users/*}",
    status_decisao: "adicionar",
    justificativa: "Remove acesso de usuário e é destrutivo.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts.users/delete`,
    observacoes_para_ravi_dev: "Permissão administrativa destrutiva dedicada.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["program-enable", "program-disable"],
    categoria: "programs",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Accounts v1 programs enable/disable",
    status_decisao: "adicionar",
    justificativa: "Ativação de programas muda distribuição comercial.",
    fonte_oficial: `${REST_REFERENCE}/accounts_v1/accounts.programs`,
    observacoes_para_ravi_dev: "Tratar disable como write de alto risco, com confirmação específica.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["notifications", "notification"],
    categoria: "notifications",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Notifications v1 get/list methods",
    status_decisao: "adicionar",
    justificativa: "Notifications v1 é estável.",
    fonte_oficial: `${DISCOVERY}?version=notifications_v1`,
    observacoes_para_ravi_dev: "Adicionar quando houver consumer de eventos definido.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["notification-create", "notification-update"],
    categoria: "notifications",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Notifications v1 create/patch methods",
    status_decisao: "adicionar",
    justificativa: "Criação/alteração de subscription tem side effects externos.",
    fonte_oficial: `${DISCOVERY}?version=notifications_v1`,
    observacoes_para_ravi_dev: "Validar callback e ownership antes de liberar.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["notification-delete"],
    categoria: "notifications",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Notifications v1 delete method",
    status_decisao: "adicionar",
    justificativa: "Delete interrompe notificações.",
    fonte_oficial: `${DISCOVERY}?version=notifications_v1`,
    observacoes_para_ravi_dev: "Permissão destrutiva e confirmação obrigatórias.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["lfp-stores", "lfp-store", "lfp-merchant-state", "lfp-providers-find"],
    categoria: "local-feeds-partnership",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "LFP v1 + Accounts v1 omnichannel LFP resources",
    status_decisao: "adicionar",
    justificativa: "Contratos estáveis existem, embora possam exigir allowlist da conta.",
    fonte_oficial: `${DISCOVERY}?version=lfp_v1`,
    observacoes_para_ravi_dev: "Falhar fechado em 403; não usar fallback autenticado do SDE.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["lfp-inventory-insert", "lfp-sale-insert", "lfp-store-insert"],
    categoria: "local-feeds-partnership",
    risco_read_write: "financial",
    endpoint_ou_recurso_oficial: "LFP v1 insert methods",
    status_decisao: "adicionar",
    justificativa: "Inventário e venda LFP carregam dados comerciais e devem usar permissão financeira isolada.",
    fonte_oficial: `${DISCOVERY}?version=lfp_v1`,
    observacoes_para_ravi_dev: "Nunca executar em teste; desenhar idempotência e confirmação antes da Fase 3.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["lfp-store-delete"],
    categoria: "local-feeds-partnership",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "LFP v1 store delete",
    status_decisao: "adicionar",
    justificativa: "Remove loja do relacionamento LFP.",
    fonte_oficial: `${DISCOVERY}?version=lfp_v1`,
    observacoes_para_ravi_dev: "Permissão destrutiva e confirmação obrigatórias.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["product-reviews", "product-review", "merchant-reviews", "merchant-review"],
    categoria: "reviews",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Reviews v1alpha",
    status_decisao: "estudar",
    justificativa: "A fonte oficial atual marca Reviews v1beta como descontinuada e v1alpha como ativa/experimental.",
    fonte_oficial: VERSIONING,
    observacoes_para_ravi_dev: "Não copiar v1beta do SDE; exigir decisão explícita antes de adotar alpha.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["product-review-insert", "merchant-review-insert"],
    categoria: "reviews",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Reviews v1alpha",
    status_decisao: "estudar",
    justificativa: "Write só existe em versão alpha ativa no ciclo oficial atual.",
    fonte_oficial: VERSIONING,
    observacoes_para_ravi_dev: "Não implementar sem aprovação de adoção alpha e contrato exato revisado.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["product-review-delete", "merchant-review-delete"],
    categoria: "reviews",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Reviews v1alpha",
    status_decisao: "estudar",
    justificativa: "Delete em API alpha combina instabilidade e irreversibilidade.",
    fonte_oficial: VERSIONING,
    observacoes_para_ravi_dev: "Aguardar contrato estável ou aprovação explícita com gate destrutivo.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["tos-agreement-state", "tos-retrieve-for-app"],
    categoria: "terms-of-service",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Accounts v1 termsOfServiceAgreementStates",
    status_decisao: "adicionar",
    justificativa: "Métodos de leitura estão confirmados em accounts v1.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev: "Separar consulta de qualquer aceite de ToS.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["product-issues-render"],
    categoria: "issue-resolution",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Issue resolution v1 renderProductIssues",
    status_decisao: "adicionar",
    justificativa: "Issueresolution v1 é estável e o render é read-only.",
    fonte_oficial: `${DISCOVERY}?version=issueresolution_v1`,
    observacoes_para_ravi_dev: "Não confundir com execução de action.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["issue-action"],
    categoria: "issue-resolution",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Issue resolution v1 triggerAction",
    status_decisao: "adicionar",
    justificativa: "A ação muta estado e precisa de fluxo HITL específico.",
    fonte_oficial: `${DISCOVERY}?version=issueresolution_v1`,
    observacoes_para_ravi_dev: "Nunca derivar actionId de texto livre; confirmação obrigatória.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["aggregate-statuses"],
    categoria: "issue-resolution",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Issue resolution v1 aggregateProductStatuses",
    status_decisao: "adicionar",
    justificativa: "Método v1 confirmado, complementar ao ProductStatus individual.",
    fonte_oficial: `${DISCOVERY}?version=issueresolution_v1`,
    observacoes_para_ravi_dev: "Adicionar como relatório tipado se houver uso diário.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["quotas", "quota-limits", "quota-limit"],
    categoria: "quota",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Quota v1 quotaGroups and limits",
    status_decisao: "adicionar",
    justificativa: "Quota v1 é estável e útil para health operacional.",
    fonte_oficial: `${DISCOVERY}?version=quota_v1`,
    observacoes_para_ravi_dev: "Boa candidata a health futuro, sem autenticação na Fase 1.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["developer-registration", "gcp-account", "gbp-accounts"],
    categoria: "developer-and-links",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Accounts v1 developerRegistration/gbpAccounts",
    status_decisao: "adicionar",
    justificativa: "Leituras oficiais existem, mas pertencem ao onboarding da Fase 2.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev: "Não expor project id ou identidade como segredo; aplicar redaction.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["gcp-register", "gcp-unregister", "gbp-account-link"],
    categoria: "developer-and-links",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Accounts v1 developerRegistration/gbpAccounts mutations",
    status_decisao: "aguardar",
    justificativa: "São parte do onboarding de autenticação e linking, excluídos da Fase 1.",
    fonte_oficial: `${DISCOVERY}?version=accounts_v1`,
    observacoes_para_ravi_dev: "Implementar somente com desenho de credencial e aprovação explícita.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["ps-text-suggestions", "ps-image-background", "ps-image-remove-background", "ps-image-upscale"],
    categoria: "product-studio",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Product Studio v1alpha",
    status_decisao: "estudar",
    justificativa: "A fonte oficial confirma somente versão alpha ativa, sem estabilidade de contrato.",
    fonte_oficial: VERSIONING,
    observacoes_para_ravi_dev: "Não inventar endpoints nem adotar alpha sem decisão explícita.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["order-tracking-create"],
    categoria: "order-tracking",
    risco_read_write: "financial",
    endpoint_ou_recurso_oficial: "POST ordertracking/v1/{parent}/orderTrackingSignals",
    status_decisao: "migrar",
    justificativa: "Método v1 confirmado; carrega dados de pedido e fulfillment.",
    fonte_oficial: `${REST_REFERENCE}/ordertracking_v1/accounts.orderTrackingSignals/create`,
    observacoes_para_ravi_dev: "Permissão financeira isolada, redaction de PII e confirmação obrigatórias.",
    operacao_ravi: "merchant.order-tracking-create",
  },
  {
    operacoes_sde: ["css-products", "css-product-get", "css-account", "css-child-accounts", "css-labels", "css-quotas"],
    categoria: "comparison-shopping-services",
    risco_read_write: "read",
    endpoint_ou_recurso_oficial: "Contrato não confirmado no diretório Merchant API atual",
    status_decisao: "estudar",
    justificativa: "CSS não aparece entre as sub-APIs Merchant confirmadas pela fonte oficial consultada.",
    fonte_oficial: "https://discovery.googleapis.com/discovery/v1/apis?name=merchantapi",
    observacoes_para_ravi_dev: "Auditar a API oficial CSS separadamente antes de criar qualquer endpoint.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: [
      "css-product-insert",
      "css-product-patch",
      "css-account-labels",
      "css-label-create",
      "css-label-patch",
    ],
    categoria: "comparison-shopping-services",
    risco_read_write: "write",
    endpoint_ou_recurso_oficial: "Contrato não confirmado no diretório Merchant API atual",
    status_decisao: "estudar",
    justificativa: "Não há contrato oficial Merchant atual verificado para estas mutações.",
    fonte_oficial: "https://discovery.googleapis.com/discovery/v1/apis?name=merchantapi",
    observacoes_para_ravi_dev: "Não implementar até auditoria oficial dedicada.",
    operacao_ravi: null,
  },
  {
    operacoes_sde: ["css-product-delete", "css-label-delete"],
    categoria: "comparison-shopping-services",
    risco_read_write: "destructive",
    endpoint_ou_recurso_oficial: "Contrato não confirmado no diretório Merchant API atual",
    status_decisao: "aguardar",
    justificativa: "Delete não pode ser inferido do legado sem fonte oficial atual.",
    fonte_oficial: "https://discovery.googleapis.com/discovery/v1/apis?name=merchantapi",
    observacoes_para_ravi_dev: "Bloqueado até contrato CSS oficial e gate destrutivo específico.",
    operacao_ravi: null,
  },
];

export const merchantOperationMatrix: MerchantOperationMatrixEntry[] = groups.flatMap(({ operacoes_sde, ...entry }) =>
  operacoes_sde.map((operacao_sde) => ({ operacao_sde, ...entry })),
);
